language: python
python:
- '3.5'
- '3.6'
install:
- pip install -e .
- pip install -r test_requirements.txt
script:
- pylint --rcfile=.pylintrc layercake tests setup.py
- pytest tests
deploy:
  provider: pypi
  user: spatz
  password:
    secure: HErZCWyxO+Yk5hIvS+1ZYcqV73A2/qH34Hs8zzb9BuHKIB0ZCCVd4Tzk+jKCzMhqeq05/Wuebk9HC4zjb8GmtHwU/tzQ8KHKM6/h8sWeTDg5jNLCPEu5sCujQUHB0IbmY0sxECmtNDWvKrXNIdD9W/CSlV92Fzh7kvZHDfqyL1JNPDL12hqB6FXioxCUYtw+RMMs5ZvzxArc1n7/L0RiNY1GcRkkm03rM06zTU3A+rjMleTzpN1QujcAHU/C/rb9O6dH5H4Nuj0C4eZzNQ98dqk+Y8W3eyTovZ1nOBmIuuB4PUEpXaCy/8fpCYv3SeV1uGEKY+7n0ic9TldAswpInDpda9G594K0jW7i7Hs+/HnTQPkPqyXOrozHHHUlXahq+pbGjYxPb4LngJY6pXywoLs0L5In30k3CJYrjkbdofvGm5SK/8vOTbd0hYRckztnYN2RH2Y7lRvyTSdo83NPHHJpI20e81yFd/RxFDhHsF2PblqioC+z7Obth1dVJlMO6b8S4uYuv9FVUUmTgca3UuFX/HCQ98u5r6tORfpqsUAnf1FkMGkkCPOwZXkXrV3/lhKyd6WhdtySpyYZl8ECcjJuFf3YTZs0T/JqF+z8Xdrz5+y8M9bNkbb3EwQQLg0Mgi2TIDkGoq73NvlE0MarLaVvYLrlHDQv8SHHXL/f06o=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: getslash/layercake
